version: '3.8'
services:
  mysql-master:
    build:
      context: ./
      dockerfile: docker/master/Dockerfile
    restart: always
    environment:
      MYSQL_DATABASE: bidnamu
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - master:/var/lib/mysql
      - master:/var/lib/mysql-files
    networks:
      - net-mysql

  mysql-slave:
    build:
      context: ./
      dockerfile: docker/slave/Dockerfile
    restart: always
    environment:
      MYSQL_DATABASE: bidnamu
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3308:3306"
    volumes:
      - slave:/var/lib/mysql
      - slave:/var/lib/mysql-files
    networks:
      - net-mysql

  redis-cache:
    image: redis:7.2-alpine
    command: redis-server --port 6379
    ports:
      - "6379:6379"

  redis-session:
    image: redis:7.2-alpine
    command: redis-server --port 6380
    ports:
      - "6380:6380"

volumes:
  master:
  slave:

networks:
  net-mysql:
    driver: bridge
