version: '3.8'
services:
  mysql-master:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bidnamu
    ports:
      - "3307:3306"

  mysql-slave:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bidnamu
    ports:
      - "3308:3306"

  redis-cache:
    image: redis:7.2-alpine
    command: redis-server --port 6379
    ports:
      - "6379:6379"

  redis-session:
    image: redis:7.2-alpine
    command: redis-server --port 6380
    ports:
      - "6380:6380"
