spring:
  datasource:
    master:
      hikari:
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3307/bidnamu
        username: user
        password: password

    slave:
      hikari:
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3308/bidnamu
        username: user
        password: password

  redis:
    cache:
      host: localhost
      port: 6379
    session:
      host: localhost
      port: 6380

  jpa:
    hibernate:
      ddl-auto: create